#!/usr/bin/ksh
# Author : Bernard Polarski
# Date   : 17-Jul-2000
# Modified   : BPA - 16-Nov-2000        : added fifth level

# This program generated automatically and smenu_index.html from FIN

#--------------------------------------------------------
write_c_d()
{
   #set -xv
   stop="stop 4"
   var=`expr $LEVEL \* 3`
   SPC=`echo $var| awk '{ spc=substr("            ",1,$1);
                          printf("%s",spc) ; }'`
   case $b in
      'C' ) echo "${SPC}   <li> $c $d "       >> $FOUT ;;
      'H' ) TARGET=`echo $c |sed 's/\.sh/_sh.txt/'`
            echo "${SPC}   <li> $d <A href=\"$TARGET\"> [Shell] </A>"       >> $FOUT ;;
      'HP' ) TARGET=`echo $c |sed 's/\.hlp/_hlp.txt/'`
            echo "${SPC}   <li> $d <A href=\"$TARGET\"> [Text] </A>"       >> $FOUT ;;
      'Q' ) TARGET=`echo $c |sed 's/\.sql/_sql.txt/'`
            echo "${SPC}   <li> $d <A href=\"$TARGET\"> [SQL] </A>"         >> $FOUT ;;
      'HQ') TARGET=`echo $c |sed 's/\.sh/_sh.txt/'`
            echo "${SPC}   <li> $d <A href=\"$TARGET\"> [Shell/SQL] </A>"   >> $FOUT ;;
      'SQ') TARGET=`echo $c |sed 's/\.sh/_sh.txt/'`
            TARGET2=`echo $c |sed 's/\.sh/_sql.txt/'`
            echo "${SPC}   <li> $d <A href=\"$TARGET\"> [Shell]</A><A href=\"$TARGET2\">[SQL] </A>"   >> $FOUT ;;
      'T' ) echo "${SPC}   <li> $d <A href=\"$c\"> [Text] </A>"   >> $FOUT ;;
      'M')  echo "$SPC <!------ $a ------------>" >> $FOUT
            echo "${SPC}   <li><b> $c $d </b>"                                      >> $FOUT 
            echo "${SPC}     <OL>" >> $FOUT
            OLD_LEVEL=`expr $OLD_LEVEL + 1`
            ;;
      'M1')  echo "$SPC <!------ $a ------------>" >> $FOUT
            echo "${SPC}   <li><font size=\"+1\" color=\"brown\"> $c $d </font>" >> $FOUT 
            echo "${SPC}     <OL>" >> $FOUT
            OLD_LEVEL=`expr $OLD_LEVEL + 1`
            ;;
   esac
}
#--------------------------------------------------------
rupt()
{
   if [   ! "x-$L1" = "x-$OL1" ] ;then
          dif=1
   elif [ ! "x-$L2" = "x-$OL2" ] ;then
          dif=2
   elif [ ! "x-$L3" = "x-$OL3" ] ;then
          dif=3
   elif [ ! "x-$L4" = "x-$OL4" ] ;then
          dif=4
   elif [ ! "x-$L5" = "x-$OL5" ] ;then
          dif=5
   else
          dif=0
   fi
   echo $dif
}
#--------------------------------------------------------
FIN=$SBIN/data/smenu_master_menu_index.txt
FOUT=$SBIN/tmp/smenu_index.html
> $FOUT
L1=0
L2=0
L3=0
L4=0
L5=0
OL1=-1
OL2=-1
OL3=-1
OL4=-1
OL5=-1
LEVEL=1
OLD_LEVEL=0
SPC4="    "
SPC8="        "
SPC12="            "
cat >> $FOUT <<EOF

<head>
<title>Smenu Contents</title>
<meta name="author" content="Bernard Polarski">
<meta name="keywords" content="Oracle Shell scripts">
</head>
<body bgcolor="#FFFFFF" link="#0000FF" vlink="#FF0000" text="#000000">
<!---------------------------------------------------------------->
<!---- This page is generated by Smenu Self document function ---->
<!---------------------------------------------------------------->
<table border=0 cellspacing=0 cellpadding=0 width=700>
<tr valign="top" align="left"><td colspan=30 height=7> 
<td>
<A href="/SiliconValley/Mouse/3936/features_1.html"> Automated explain plan" </A>
</td>
<td>
<A href="/SiliconValley/Mouse/3936/features_2.html">Backup with Smenu</A>
</td>
<td>
<A href="/SiliconValley/Mouse/3936/features_3.html"> Instruction Generator</A>
</td>
<td>
<A href="/SiliconValley/Mouse/3936/features_4.html">Shortcuts in Smenu</A>
</td>
</tr>
</table>
<!------------------------------------------------------------->
<table border=0 cellspacing=0 cellpadding=0 width=700>



<tr valign="top" align="left">
<tr valign="middle" align="left">
   <td width=110 align="center"  valign="middle">
       <img height=90 width=100   
            src="/clipart/pbi/pictures/Animals/camel.gif"
            border=0
            alt="/clipart/pictures/Animals/camel.gif"></td>
   
   <td  valign=middle width=432>


    <table border=0>
       <tr><td height=25></td></tr>
       <tr><td height=32 bgcolor="#003399" 
               align="center" width=432>           
           <p>
           <font color=#FFFFCC size="+1">
                <u>Menu </u> </font>
      <font size="+1" color=white><u>Contents </u></font> 
 </td>
       </tr>
       <tr><td height=25></td></tr>
     </table>


   <td width=100 align="center" align="middle"> 
      <img height=90 width=100 
      src="/clipart/pbi/pictures/Animals/camel.gif" border=0
      alt="/clipart/pictures/Animals/camel.gif"></td>
</tr>
<tr valign="top" align="left">
    <td colspan=30 height=7></td>
</tr>
</table>

<table border=0 cellspacing=0 cellpadding=0 width=600>

<tr valign="top" align="left">

   <td colspan=5 width=100 bgColor="#FFFFCC">

<!----(nav)---------------- colone de gauche------------------------->

<table width=100><tr><td height=15></td></tr></table>

<table width=100><tr><td>
<a href="/SiliconValley/Mouse/3936/Installation_guides.html">Installation instructions</a>
</td></tr></table>

<table width=100><tr><td height=15></td></tr></table>
<table width=100><tr><td>
<a href="/SiliconValley/Mouse/3936/screenshots.html">Screenshots</a></td>
</td></tr></table>

<table width=100><tr><td height=15></td></tr></table>
<table width=100><tr><td>
<a href="/SiliconValley/Mouse/3936/todo.html">Todo Lists</a></td>
</td></tr></table>

<table width=100><tr><td height=15></td></tr></table>
<table width=100><tr><td>
<a href="/SiliconValley/Mouse/3936/history.html">History</a></td>
</td></tr></table>

<table width=100><tr><td height=15></td></tr></table>
<table width=100><tr><td>
<a href="/SiliconValley/Mouse/3936/smenu_tar.tgz">Download smenu</a>
</td></tr></table>

<table width=100><tr><td height=15></td></tr></table>
<table width=100><tr><td>
<a href="/SiliconValley/Mouse/3936/links.html">Links</a></td>
</td></tr></table>

<table width=100><tr><td height=15></td></tr></table>
<table width=100><tr><td>
<a href="http://www.geocities.com/bpolarsk/index.html">
Home</a></td></td></tr></table>


<!-- fin colone de gauche (navigations)-->
   </td>

<!------------------- Debut colone de droite (main)------------------->

   <td colspan=25>

<table border=0 cellspacing=0 cellpadding=5 width=600>
<tr valign="top" align="left" bgcolor=#cccccc>
<center>
<tr><td colspan=3>
<td colspan=24>
<table border=1 cellspacing=0 cellpadding=15 width=480>
          <td valign=middle > 
         This section list the content of each module.  We Give also most control Shell script as it may serve as example on how to control SQL script flow. <small><i>(The full content is availble for download in one gzip tar file)</i> </smal>    </font></td></tr></table>
</td>
<td colspan=3></td></tr>  
</center>
</table>

<table border=0 cellspacing=0 cellpadding=5 width=600>
<tr><td height=10></td></tr>
</table>
<table border=0 cellspacing=0 cellpadding=5 width=600>
<TR> <TD colspan=1> </TD>
<OL>
EOF
# ---- example of the input file for the loop : ----------------------------------------
#1.7.8 M Plan a backup                       (sub)
#1.7.8.l H scripts/backup/smenu_view_actions.sh List existing Backup actions
#1.7.8.2 H scripts/backup/smenu_create_export_action.sh Create an export backup action
#1.7.8.3 H scripts/backup/smenu_create_cold_action.sh Create a cold backup action
#----------------------------------------------------------------------------------------
while read a b c d 
  do 
   if [ `echo $a |cut -c1` = '#' ];then
      continue
   fi
   echo "level=$LEVEL : $a $b $c $d $e"
   L1=`echo $a | cut -f1 -d'.'`
   L2=`echo $a | awk -F'.' '{ print $2}'`
   L3=`echo $a | awk -F'.' '{ print $3}'`
   L4=`echo $a | awk -F'.' '{ print $4}'`
   L5=`echo $a | awk -F'.' '{ print $5}'`
   LEVEL=`rupt`
   if [ $OLD_LEVEL -gt $LEVEL ];then
        i=$OLD_LEVEL
        while [ $i -gt $LEVEL ]
         do
           var=`expr $i \* 3`
           #var=`expr $var - 2`
           SPC=`echo $var| awk '{ spc=substr("            ",1,$1);
                                  printf("%s",spc) ; }'`
           echo "$SPC  </OL>" >> $FOUT
           i=`expr $i - 1`
         done
   fi
   write_c_d
   OLD_LEVEL=$LEVEL
   OL1=$L1
   OL2=$L2
   OL3=$L3
   OL4=$L4
   OL5=$L5
done< $FIN
echo "   </OL> " >> $FOUT
echo "</OL> " >> $FOUT
DATE=`date +%d-%b-%Y`

cat >> $FOUT <<EOF
     <TD colspan=27 rowspan=1> </TD>
</TR>
</TABLE>
<!------------------------------------------------------------>
<!------------------------------------------------------------>
<!------------------------------------------------------------>


<TR valign="top" align="left">
	<TD colspan=30 height=29></TD>
</TR>

<TR valign="top" align="left">
	<TD colspan=1 height=1></TD>
	<TD colspan=26 rowspan=1 width=694><!-- hr -->
<HR></TD>
	<TD colspan=3 height=1></TD>
</TR>
<TR valign="top" align="left">
	<TD colspan=30 height=9></TD>
</TR>

<TR valign="top" align="left">
	<TD colspan=4 rowspan=3 width=10> 
        </TD>
        <TD colspan=2 width=20> </TD>
	<TD colspan=5 rowspan=3 width=120 align=center>
            <a href="mailto:bpolarsk@yahoo.com">
            bpolarsk@yahoo.com</a></TD>
        <TD colspan=2 width=20> </TD>
	<TD colspan=17 width=180 align=left>
            <font size="-1">
            <p>Last Update : $DATE</p></font></TD>
	<TD colspan=13></TD>
</TR>

</TD></TR></table></td></TR>
</table>
</body></html>
EOF

if $SBIN/scripts/yesno.sh "to view FOUT" DO Y
   then
    vi $FOUT
fi
